import React from 'react'

export const mealList = [
    {
        index:0,
        title:'아침 메뉴'
    },
    {
        index:1,
        title:'점심 메뉴'
    },
    {
        index:2,
        title:'저녁 메뉴'
    },
    {
        index:3,
        title:'간식 메뉴'
    },
]

export const breakfastList = [
    {
        index:0,
        title: '한식'
    },
    {
        index:1,
        title: '일식'
    },
    {
        index:2,
        title: '중식'
    },
    {
        index:3,
        title: '양식'
    },
    {
        index:4,
        title: '탕-찌게'
    },
    {
        index:5,
        title: '해장'
    },
    {
        index:6,
        title: '간편식'
    },
    {
        index:7,
        title: '기타'
    },
]

export const FoodList = [
    {
        indx:0,
        list:[
            {
                index:0,
                title:'불고기'
            },
            {
                index:1,
                title:'오징어 두루치기'
            },
            {
                index:2,
                title:'닭볶음'
            },
            {
                index:3,
                title:'쌈밥'
            },
            {
                index:4,
                title:'비빔밥'
            },
            {
                index:5,
                title:'생선구이'
            },
            {
                index:6,
                title:'낙지볶음'
            },
            {
                index:7,
                title:'게장'
            },
            {
                index:8,
                title:'떡갈비'
            },
        ]
    },
    {
        indx:1,
        list:[
            {
                index:0,
                title:'초밥'
            },
            {
                index:1,
                title:'초밥'
            },
            {
                index:2,
                title:'초밥'
            },
            {
                index:3,
                title:'초밥'
            },
            {
                index:4,
                title:'초밥'
            },
            {
                index:5,
                title:'초밥'
            },
            {
                index:6,
                title:'초밥'
            },
            {
                index:7,
                title:'초밥'
            },
            {
                index:8,
                title:'초밥'
            },
        ]
    },
    {
        indx:2,
        list:[
            {
                index:0,
                title:'짜장면'
            },
            {
                index:1,
                title:'짬뽕'
            },
            {
                index:2,
                title:'볶음밥'
            },
            {
                index:3,
                title:'탕수육'
            },
            {
                index:4,
                title:'마파두부'
            },
            {
                index:5,
                title:'양장피'
            },
            {
                index:6,
                title:'깐풍기'
            },
            {
                index:7,
                title:'유린기'
            },
            {
                index:8,
                title:'고추잡채'
            },
        ]
    },
    {
        indx:3,
        list:[
            {
                index:0,
                title:'토마토 스파게티'
            },
            {
                index:1,
                title:'봉골레'
            },
            {
                index:2,
                title:'크림 파스타'
            },
            {
                index:3,
                title:'피자'
            },
            {
                index:4,
                title:'함박 스테이크'
            },
            {
                index:5,
                title:'리조또'
            },
            {
                index:6,
                title:'스테이크'
            },
            {
                index:7,
                title:'햄버거'
            },
            {
                index:8,
                title:'시저 샐러드'
            },
        ]
    },
    {
        indx:4,
        list:[
            {
                index:0,
                title:'김치찌개'
            },
            {
                index:1,
                title:'순두부 찌개'
            },
            {
                index:2,
                title:'된장찌개'
            },
            {
                index:3,
                title:'부대찌개'
            },
            {
                index:4,
                title:'동태찌개'
            },
            {
                index:5,
                title:'청국장'
            },
            {
                index:6,
                title:'갈비탕'
            },
            {
                index:7,
                title:'추어탕'
            },
            {
                index:8,
                title:'삼계탕'
            },
        ]
    },
    {
        indx:5,
        list:[
            {
                index:0,
                title:'북엇국'
            },
            {
                index:1,
                title:'콩나물 국밥'
            },
            {
                index:2,
                title:'순대국'
            },
            {
                index:3,
                title:'뼈해장국'
            },
            {
                index:4,
                title:'우거지국'
            },
            {
                index:5,
                title:'선지 해장국'
            },
            {
                index:6,
                title:'올갱이국'
            },
            {
                index:7,
                title:'매운 라면'
            },
            {
                index:8,
                title:'물냉면'
            },
        ]
    },
    {
        indx:6,
        list:[
            {
                index:0,
                title:'편의점 도시락'
            },
            {
                index:1,
                title:'샌드위치'
            },
            {
                index:2,
                title:'토스트'
            },
            {
                index:3,
                title:'샐러드'
            },
            {
                index:4,
                title:'김밥'
            },
            {
                index:5,
                title:'떡볶기'
            },
            {
                index:6,
                title:'핫도그'
            },
            {
                index:7,
                title:'밥버거'
            },
            {
                index:8,
                title:'시리얼'
            },
        ]
    },
    {
        indx:7,
        list:[
            {
                index:0,
                title:'쌀국수'
            },
            {
                index:1,
                title:'팟타이'
            },
            {
                index:2,
                title:'카레'
            },
            {
                index:3,
                title:'찜닭'
            },
            {
                index:4,
                title:'수제비'
            },
            {
                index:5,
                title:'칼국수'
            },
            {
                index:6,
                title:'아구찜'
            },
            {
                index:7,
                title:'닭갈비'
            },
            {
                index:8,
                title:'월남쌈'
            },
        ]
    },


]